const Genres = [
    'action',
    'adventure',
    'cars',
    'comedy',
    'crime',
    'dementia',
    'demons',
    'drama',
    'dub',
    'family',
    'fantasy',
    'game',
    'gourmet',
    'harem',
    'hentai',
    'historical',
    'horror',
    'josei',
    'kids',
    'magic',
    'martial-arts',
    'mecha',
    'military',
    'music',
    'mystery',
    'parody',
    'police',
    'psychological',
    'romance',
    'samurai',
    'school',
    'sci-fi',
    'seinen',
    'shoujo',
    'shoujo-ai',
    'shounen',
    'shounen-ai',
    'slice-of-Life',
    'space',
    'sports',
    'super-power',
    'supernatural',
    'suspense',
    'thriller',
    'vampire',
    'yaoi',
    'yuri',
    'isekai',
    "Ecchi",
    "adult-cast",
    "anthropomorphic",
    "avant-garde",
    "boys-love",
    "cgdct",
    "childcare",
    "comic",
    "crossdressing",
    "delinquents",
    "detective",
    "erotica",
    "gag-humor",
    "gender-bender",
    "gore",
    "high-stakes-game",
    "iyashikei",
    "mahou-shoujo",
    "medical",
    "mythology",
    "organized-crime",
    "performing-arts",
    "pets",
    "racing",
    "reincarnation",
    "romantic-subtext",
    "showbiz",
    "strategy-game",
    "survival",
    "team-sports",
    "time-travel",
    "video-game",
    "visual-arts",
    "work-life",
    "workplace",
]


const MoviesSort = [
    { name:"all",value: "" },
    { name:"zero",value: "0" },
    { name: "a", value: "a" },
    { name:"b", value: "b" },
    { name:"c", value: "c" },
    { name:"d", value: "d" },
    { name:"e", value: "e" },
    { name:"f", value: "f" },
    { name:"g", value: "g" },
    { name:"h", value: "h" },
    { name:"i", value: "i" },
    { name:"j", value: "j" },
    { name:"k", value: "k" },
    { name:"l", value: "l" },
    { name:"m", value: "m" },
    { name:"n", value: "n" },
    { name:"o", value: "o" },
    { name:"p", value: "p" },
    { name:"q", value: "q" },
    { name:"r", value: "r" },
    { name:"s", value: "s" },
    { name:"t", value: "t" },
    { name:"u", value: "u" },
    { name:"v", value: "v" },
    { name:"w", value: "w" },
    { name:"x", value: "x" },
    { name:"y", value: "y" },
    { name:"z", value: "z" }
]

const zIndex ={
    HIGH: 11,
    TOP: 10,
    CENTER: 9,
    BELOW: 8,
}

export {Genres,MoviesSort,zIndex}